In [4]:
import pandas as pd
import numpy as np
df = pd.read_csv('raw_data.csv')

In [2]:
df.head()

,Unnamed: 0,hotel_name,review,address,prices,location,cleanliness,service,value
0,0,1. The Papandayan,5.0,"Jl. Gatot Subroto 83, Bandung 40262 Indonesia",694827,4.5,4.5,4.7,0.0
1,1,2. The Gaia Hotel Bandung,5.0,"No. 430 Jl. Dr. Setiabudi, Bandung 40143 Indon...",1054558,4.9,4.8,4.9,0.0
2,2,3. Janevalla Bandung,4.5,"Jalan Aceh No. 65, Jawa Barat, Bandung 40115 I...",603803,4.7,4.6,4.6,0.0
3,3,4. Grand Tjokro Premiere Bandung,4.5,"Jl. Cihampelas no. 211-217, Bandung 40131 Indo...",505393,4.5,4.4,4.4,0.0
4,4,5. Swiss-Belresort Dago Heritage,5.0,Lapangan Golf Dago Atas No. 78 Dago Heritage G...,939250,4.8,4.3,4.6,0.0

In [5]:
def splitting(s):
  s['hotel_name'] = s['hotel_name'].split('.')[1]
  return s

def splitting2(s):
  s['address'] = s['address'].split('/"')[0]
  return s

df = df[df.hotel_name != 'None']
df = df[df.review != '0.0']
df = df[df.address != 'None']
df = df[df.prices != 0]
df.drop(df.columns[df.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)
df = df.apply(splitting , axis = 1)
df = df.apply(splitting2 , axis = 1)
print(df)
df.to_csv('data_cleansed.csv', index=False)

                        hotel_name  review  \
0                   The Papandayan     5.0
1           The Gaia Hotel Bandung     5.0
2                Janevalla Bandung     4.5
3    Grand Tjokro Premiere Bandung     4.5
4    Swiss-Belresort Dago Heritage     5.0
..                             ...     ...
85                     HAY Bandung     4.0
86                 De Batara Hotel     3.5
87      Grand Aquila Hotel Bandung     3.5
88              Green Batara Hotel     3.5
89               Vio Hotel Pasteur     3.5

                                              address   prices  location  \
0       Jl. Gatot Subroto 83, Bandung 40262 Indonesia   694827       4.5
1   No. 430 Jl. Dr. Setiabudi, Bandung 40143 Indon...  1054558       4.9
2   Jalan Aceh No. 65, Jawa Barat, Bandung 40115 I...   603803       4.7
3   Jl. Cihampelas no. 211-217, Bandung 40131 Indo...   505393       4.5
4   Lapangan Golf Dago Atas No. 78 Dago Heritage G...   939250       4.8
..                                                ...      ...       ...
85      Jl. Trunojoyo no. 19, Bandung 40115 Indonesia   550659       5.0
86    Jl. Cihampelas no. 112, Bandung 40116 Indonesia   227311       4.4
87     Jl. DR Djundjunan 116, Bandung 40163 Indonesia   685736       3.9
88    Jln. Cihampelas no 145, Bandung 40131 Indonesia   216406       4.5
89  Jl. Dr Jungjunan no. 154 Pasteur, Bandung 4016...   366571       3.7

    cleanliness  service  value
0           4.5      4.7    0.0
1           4.8      4.9    0.0
2           4.6      4.6    0.0
3           4.4      4.4    0.0
4           4.3      4.6    0.0
..          ...      ...    ...
85          4.2      4.0    0.0
86          3.9      3.9    0.0
87          3.3      3.7    0.0
88          3.7      3.7    0.0
89          3.4      3.3    0.0

[87 rows x 8 columns]