In [1]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By

In [2]:
#Mengirim request get
driver = webdriver.Chrome()
driver.get('https://liquipedia.net/valorant/VCT/2023/Pacific_League/Statistics')

# Player Statistics

In [3]:
#Mendapatkan data nickname pemain
playerNames = driver.find_elements(By.XPATH,'//tbody/tr/td[1]/a')

for playerName in playerNames:
    print(playerName.text)

Sayaplayer
something
Foxy9
Jinggg
SkRossi
BuZz
f0rsakeN
Dep
t3xture
Suggest
Meteor
Seoldam
Monyet
xffero
MaKo
garnetS
EJAY
Benkai
Munchkin
k1Ng
patt
Lmemore
d4v41
Jremy
xeta
Sylvan
SugarZ3ro
Crws
fl1pzjder
Bazzi
foxz
GodDead
invy
TENNN
WRONSKI
sushiboys
Anthem
iNTRO
JitboyS
ban
TS
DubsteP
Rb
takej
Lightningfast
Zest
CigaretteS
Emman
Carpe
stax
BORKUM
Reita
mindfreak
AYRIN
Laz
2ge
eKo
xnfri
JessieVash
crow
lenne

In [46]:
#Memasukkan data nickname pemain ke dalam array
list = []

for each in playerNames:
    list.append(each.text)

print(list)

['Sayaplayer', 'something', 'Foxy9', 'Jinggg', 'SkRossi', 'BuZz', 'f0rsakeN', 'Dep', 't3xture', 'Suggest', 'Meteor', 'Seoldam', 'Monyet', 'xffero', 'MaKo', 'garnetS', 'EJAY', 'Benkai', 'Munchkin', 'k1Ng', 'patt', 'Lmemore', 'd4v41', 'Jremy', 'xeta', 'Sylvan', 'SugarZ3ro', 'Crws', 'fl1pzjder', 'Bazzi', 'foxz', 'GodDead', 'invy', 'TENNN', 'WRONSKI', 'sushiboys', 'Anthem', 'iNTRO', 'JitboyS', 'ban', 'TS', 'DubsteP', 'Rb', 'takej', 'Lightningfast', 'Zest', 'CigaretteS', 'Emman', 'Carpe', 'stax', 'BORKUM', 'Reita', 'mindfreak', 'AYRIN', 'Laz', '2ge', 'eKo', 'xnfri', 'JessieVash', 'crow', 'lenne']

In [5]:
#Mendapatkan data negara pemain
countries = driver.find_elements(By.XPATH,'//tbody/tr/td[1]/span/a/img')
countryValue = []
for country in countries:
    v = country.get_attribute('alt')
    countryValue.append(v)
print(countryValue)

['South Korea', 'Russia', 'South Korea', 'Singapore', 'India', 'South Korea', 'Indonesia', 'Japan', 'South Korea', 'South Korea', 'South Korea', 'South Korea', 'Indonesia', 'Indonesia', 'South Korea', 'Thailand', 'Philippines', 'Singapore', 'South Korea', 'South Korea', 'Thailand', 'Indonesia', 'Malaysia', 'Philippines', 'South Korea', 'South Korea', 'Japan', 'Thailand', 'Indonesia', 'South Korea', 'Thailand', 'South Korea', 'Philippines', 'Japan', 'Australia', 'Thailand', 'Japan', 'South Korea', 'Thailand', 'United States', 'South Korea', 'Philippines', 'South Korea', 'Japan', 'India', 'South Korea', 'Thailand', 'Philippines', 'South Korea', 'South Korea', 'Philippines', 'Japan', 'Indonesia', 'Canada', 'Japan', 'Philippines', 'South Korea', 'Japan', 'Philippines', 'Japan', 'Singapore']

In [7]:
#Mendapatkan data tim pemain
teams = driver.find_elements(By.XPATH,'//tbody/tr/td[2]/span/span[1]/a')
teamsValue = []
for team in teams:
    t = team.get_attribute('title')
    teamsValue.append(t)
print(teamsValue)

['T1', 'Paper Rex', 'DRX', 'Paper Rex', 'Global Esports', 'DRX', 'Paper Rex', 'ZETA DIVISION', 'Global Esports', 'DetonatioN FocusMe', 'Gen.G Esports', 'DetonatioN FocusMe', 'Global Esports', 'Rex Regum Qeon', 'DRX', 'Talon Esports', 'Rex Regum Qeon', 'Paper Rex', 'T1', 'Gen.G Esports', 'Talon Esports', 'Rex Regum Qeon', 'Paper Rex', 'Team Secret', 'T1', 'Gen.G Esports', 'ZETA DIVISION', 'Talon Esports', 'Rex Regum Qeon', 'Global Esports', 'Talon Esports', 'Gen.G Esports', 'Team Secret', 'ZETA DIVISION', 'Global Esports', 'Talon Esports', 'DetonatioN FocusMe', 'T1', 'Talon Esports', 'T1', 'Gen.G Esports', 'Team Secret', 'DRX', 'DetonatioN FocusMe', 'Global Esports', 'DRX', 'Paper Rex', 'Rex Regum Qeon', 'T1', 'DRX', 'Team Secret', 'DetonatioN FocusMe', 'Paper Rex', 'Global Esports', 'ZETA DIVISION', 'Rex Regum Qeon', 'Gen.G Esports', 'DetonatioN FocusMe', 'Team Secret', 'ZETA DIVISION', 'Team Secret']

In [8]:
#Mendapatkan data agent-agent yang dipakai pemain selama pertandingan berlangsung
agentsValue = []


for i in range(1,len(countryValue)+1):
    xpath = '//tbody/tr[' + str(i) + ']/td[3]/a'
    agents = driver.find_elements(By.XPATH,xpath)
    temp = []
    for agent in agents:
        ag = agent.get_attribute('title')
        temp.append(ag)
    agentsValue.append(temp)

print(agentsValue)

[['Jett', 'Raze'], ['Jett', 'Reyna', 'Breach'], ['Jett', 'Raze'], ['Raze', 'Phoenix', 'Sage'], ['Jett'], ['Killjoy', 'Jett', 'KAY/O'], ['Killjoy', 'Neon', 'Skye'], ['Jett', 'Raze', 'Neon'], ['Killjoy', 'Jett', 'Raze'], ['Killjoy', 'Jett', 'Raze'], ['Jett', 'Raze'], ['Jett', 'Raze'], ['Astra', 'Omen', 'Viper'], ['Astra', 'Sova', 'Skye'], ['Viper', 'Omen', 'Brimstone'], ['Jett', 'Raze', 'Neon'], ['Jett', 'Raze'], ['Breach', 'Killjoy', 'Viper'], ['Killjoy', 'Skye'], ['Killjoy', 'Viper'], ['Harbor', 'Breach', 'KAY/O'], ['Killjoy', 'Cypher', 'Viper'], ['Skye', 'Killjoy', 'Viper'], ['Raze', 'Killjoy', 'Sage'], ['Sova', 'Harbor', 'Breach'], ['Sova', 'Skye', 'Fade'], ['Omen', 'Brimstone', 'Viper'], ['Viper', 'Omen', 'Brimstone'], ['Breach', 'Skye', 'KAY/O'], ['Skye', 'Fade', 'Breach'], ['Skye', 'Sova', 'Fade'], ['KAY/O', 'Breach', 'Sage'], ['Breach', 'KAY/O', 'Skye'], ['Killjoy', 'Viper', 'Raze'], ['KAY/O', 'Jett', 'Sage'], ['Killjoy', 'Jett', 'Viper'], ['Skye', 'Killjoy', 'Breach'], ['Viper', 'Omen', 'Harbor'], ['Cypher', 'Killjoy', 'Breach'], ['Jett', 'Omen', 'Viper'], ['Omen', 'Astra'], ['Jett', 'Killjoy', 'Cypher'], ['Killjoy', 'Harbor', 'Astra'], ['Viper', 'Omen', 'Brimstone'], ['Raze'], ['Sova', 'Fade', 'Harbor'], ['Gekko'], ['Skye', 'KAY/O'], ['Skye', 'Brimstone', 'Breach'], ['Skye', 'Breach', 'KAY/O'], ['Omen', 'Astra', 'Brimstone'], ['Sova', 'Killjoy', 'Cypher'], ['Astra', 'Brimstone', 'Omen'], ['Killjoy', 'KAY/O', 'Viper'], ['Sova', 'Skye', 'Fade'], ['Astra', 'Harbor', 'Omen'], ['Breach', 'Sova'], ['Omen', 'Skye', 'Harbor'], ['Sova', 'Fade', 'Skye'], ['Breach', 'KAY/O', 'Killjoy'], ['Gekko']]

In [43]:
#Mendapatkan data-data statistik terkait pemain dan map
mapcount = driver.find_elements(By.XPATH,'//tbody/tr/td[4]')
kill = driver.find_elements(By.XPATH,'//tbody/tr/td[5]')
death = driver.find_elements(By.XPATH,'//tbody/tr/td[6]')
assist = driver.find_elements(By.XPATH,'//tbody/tr/td[7]')
kd = driver.find_elements(By.XPATH,'//tbody/tr/td[8]')
kda = driver.find_elements(By.XPATH,'//tbody/tr/td[9]')
acs = driver.find_elements(By.XPATH,'//tbody/tr/td[10]')
kpermap= driver.find_elements(By.XPATH,'//tbody/tr/td[11]')
dpermap = driver.find_elements(By.XPATH,'//tbody/tr/td[12]')
apermap = driver.find_elements(By.XPATH,'//tbody/tr/td[13]')

In [47]:
#Pembuatan tabel statistik
result = []

for i in range (len(countryValue)):
    temp_result = { 'Player Nickname' : playerNames[i].text,
                   'Country' : countryValue[i],
                   'Team' : teamsValue[i],
                   'Agents' : agentsValue[i],
                   'Maps' : mapcount[i].text,
                   'Kills' : kill[i].text,
                   'Deaths' : death[i].text,
                   'Assists' : assist[i].text,
                   'KD' : kd[i].text,
                   'KDA' : kda[i].text,
                   'ACS/Map' : acs[i].text,
                   'K/Map' : kpermap[i].text,
                   'D/Map' : dpermap[i].text,
                   'A/Map' : apermap[i].text,
                   }
    result.append(temp_result)

In [48]:
df_data = pd.DataFrame(result)
df_data

,Player Nickname,Country,Team,Agents,Maps,Kills,Deaths,Assists,KD,KDA,ACS/Map,K/Map,D/Map,A/Map
0,Sayaplayer,South Korea,T1,"[Jett, Raze]",36,642,513,117,1.25,1.47,236,17.8,14.2,3.2
1,something,Russia,Paper Rex,"[Jett, Reyna, Breach]",24,415,304,106,1.36,1.71,230,17.2,12.6,4.4
2,Foxy9,South Korea,DRX,"[Jett, Raze]",23,372,337,76,1.1,1.32,229,16.1,14.6,3.3
3,Jinggg,Singapore,Paper Rex,"[Raze, Phoenix, Sage]",29,471,411,171,1.14,1.56,227,16.2,14.1,5.8
4,SkRossi,India,Global Esports,[Jett],11,185,180,43,1.02,1.26,225,16.8,16.3,3.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,eKo,South Korea,Gen.G Esports,"[Breach, Sova]",14,169,199,106,0.84,1.38,163,12,14.2,7.5
57,xnfri,Japan,DetonatioN FocusMe,"[Omen, Skye, Harbor]",18,203,275,162,0.73,1.32,162,11.2,15.2,9
58,JessieVash,Philippines,Team Secret,"[Sova, Fade, Skye]",29,380,418,214,0.9,1.42,159,13.1,14.4,7.3
59,crow,Japan,ZETA DIVISION,"[Breach, KAY/O, Killjoy]",28,343,426,278,0.8,1.45,152,12.2,15.2,9.9
60,lenne,Singapore,Team Secret,[Gekko],1,8,13,5,0.61,1,139,8,13,5

In [49]:
#Penambahan Stats_ID
df_data.insert(0, 'Stats_ID', range(880, 880 + len(df_data)))

In [51]:
df_data

,Stats_ID,Player Nickname,Country,Team,Agents,Maps,Kills,Deaths,Assists,KD,KDA,ACS/Map,K/Map,D/Map,A/Map
0,880,Sayaplayer,South Korea,T1,"[Jett, Raze]",36,642,513,117,1.25,1.47,236,17.8,14.2,3.2
1,881,something,Russia,Paper Rex,"[Jett, Reyna, Breach]",24,415,304,106,1.36,1.71,230,17.2,12.6,4.4
2,882,Foxy9,South Korea,DRX,"[Jett, Raze]",23,372,337,76,1.1,1.32,229,16.1,14.6,3.3
3,883,Jinggg,Singapore,Paper Rex,"[Raze, Phoenix, Sage]",29,471,411,171,1.14,1.56,227,16.2,14.1,5.8
4,884,SkRossi,India,Global Esports,[Jett],11,185,180,43,1.02,1.26,225,16.8,16.3,3.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,936,eKo,South Korea,Gen.G Esports,"[Breach, Sova]",14,169,199,106,0.84,1.38,163,12,14.2,7.5
57,937,xnfri,Japan,DetonatioN FocusMe,"[Omen, Skye, Harbor]",18,203,275,162,0.73,1.32,162,11.2,15.2,9
58,938,JessieVash,Philippines,Team Secret,"[Sova, Fade, Skye]",29,380,418,214,0.9,1.42,159,13.1,14.4,7.3
59,939,crow,Japan,ZETA DIVISION,"[Breach, KAY/O, Killjoy]",28,343,426,278,0.8,1.45,152,12.2,15.2,9.9
60,940,lenne,Singapore,Team Secret,[Gekko],1,8,13,5,0.61,1,139,8,13,5

In [34]:
json_path = '../data/playerstats.json'
df_data.to_json(json_path)

In [13]:
#Mendapatkan data nama asli pemain dan tanggal ulang tahun pemain

new =[]
for i in range(len(list)):
    temp = []
    string = 'https://liquipedia.net/valorant/' + list[i]
    driver.get(string)
    pName = driver.find_element(By.XPATH,'//div/div[2]/div[1]/div[4]/div[2]')
    temp.append(pName.text)
    try:
        birth = driver.find_element(By.XPATH,"//*[contains(text(), '(age')]")
        temp.append(birth.text)
    except:
        pass
    new.append(temp)

In [14]:
dfpinfo = pd.DataFrame(new,columns=["Player Name","Birth"])
dfpinfo

             Player Name                       Birth
0                    하정우      July 29, 1998 (age 24)
1            Илья Петров  February 11, 2002 (age 21)
2                    정재성  November 20, 2004 (age 18)
3          Wang Jing Jie      July 29, 2003 (age 19)
4       Ganesh Gangadhar   October 12, 1997 (age 25)
..                   ...                         ...
56                   염왕룡                        None
57         Tomoki Moriya      March 9, 1999 (age 24)
58   Jessie Cristy Cuyco  February 21, 1990 (age 33)
59                 丸岡 智明  November 28, 1997 (age 25)
60  Lionel Lim You Xiang                        None

[61 rows x 2 columns]

In [15]:
#Memasukkan kolom nickname,negara,dan tim ke tabel playerinfo
pct = []

for i in range (len(countryValue)):
    temp_pct = { 'Player Nickname' : list[i],
                   'Country' : countryValue[i],
                   'Team' : teamsValue[i],
                   }
    pct.append(temp_pct)

dfpct = pd.DataFrame(pct)

In [16]:
dfnew = pd.concat([dfpct,dfpinfo],axis=1,join='inner')
dfnew

,Player Nickname,Country,Team,Player Name,Birth
0,Sayaplayer,South Korea,T1,하정우,"July 29, 1998 (age 24)"
1,something,Russia,Paper Rex,Илья Петров,"February 11, 2002 (age 21)"
2,Foxy9,South Korea,DRX,정재성,"November 20, 2004 (age 18)"
3,Jinggg,Singapore,Paper Rex,Wang Jing Jie,"July 29, 2003 (age 19)"
4,SkRossi,India,Global Esports,Ganesh Gangadhar,"October 12, 1997 (age 25)"
...,...,...,...,...,...
56,eKo,South Korea,Gen.G Esports,염왕룡,None
57,xnfri,Japan,DetonatioN FocusMe,Tomoki Moriya,"March 9, 1999 (age 24)"
58,JessieVash,Philippines,Team Secret,Jessie Cristy Cuyco,"February 21, 1990 (age 33)"
59,crow,Japan,ZETA DIVISION,丸岡 智明,"November 28, 1997 (age 25)"
60,lenne,Singapore,Team Secret,Lionel Lim You Xiang,None

In [49]:
jsonp_path = '../data/playerinfo.json'
dfnew.to_json(jsonp_path)