In [53]:
import requests
import pandas as pd
import warnings
import numpy as np
pd.set_option('display.max_columns', 500)
warnings.filterwarnings("ignore")

# DATA SCRAPPING

In [54]:
ucl_link = 'https://fbref.com/en/comps/8/2022-2023/stats/2022-2023-Champions-League-Stats'
data = requests.get(ucl_link)
ucl_teams = pd.read_html(data.text)[0]

In [55]:
ucl_teams

     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                  Squad               # Pl                Age
0               nl Ajax                 19               26.4
1    es Atl√©tico Madrid                 22               28.6
2          es Barcelona                 26               26.4
3      de Bayern Munich                 24               26.6
4            pt Benfica                 24               26.0
5            sct Celtic                 22               26.0
6           eng Chelsea                 26               26.9
7        be Club Brugge                 25               26.3
8      hr Dinamo Zagreb                 20               26.9
9           de Dortmund                 26               26.0
10    de Eint Frankfurt                 22               26.1
11     dk FC Copenhagen                 25               24.6
12             it Inter                 22               28.5
13          it Juventus                 26               28.3
14        de Leverkusen                 20               24.8
15        eng Liverpool                 25               27.5
16     il Maccabi Haifa                 20               28.1
17  eng Manchester City                 23               27.1
18         fr Marseille                 19               27.0
19             it Milan                 23               26.3
20            it Napoli                 22               26.4
21         fr Paris S-G                 21               27.5
22             pt Porto                 24               26.8
23          sct Rangers                 22               28.3
24        de RB Leipzig                 22               26.1
25       at RB Salzburg                 19               22.5
26       es Real Madrid                 22               27.8
27           es Sevilla                 24               28.8
28          ua Shakhtar                 20               24.3
29       pt Sporting CP                 25               25.3
30        eng Tottenham                 25               27.8
31    cz Viktoria Plze≈à                 22               28.1

   Unnamed: 3_level_0 Playing Time                    Performance          \
                 Poss           MP Starts   Min   90s         Gls Ast G+A
0                53.2            6     66   540   6.0          11   9  20
1                56.5            6     66   540   6.0           4   3   7
2                64.8            6     66   540   6.0          12  10  22
3                56.1           10    110   900  10.0          21  19  40
4                52.9           10    110   900  10.0          25  16  41
5                44.2            6     66   540   6.0           3   1   4
6                57.3           10    110   900  10.0          12   7  19
7                45.6            8     88   720   8.0           8   7  15
8                46.8            6     66   540   6.0           4   2   6
9                47.9            8     88   720   8.0          11  10  21
10               43.3            8     88   720   8.0           7   5  12
11               37.7            6     66   540   6.0           1   1   2
12               45.6           13    143  1170  13.0          19  17  36
13               48.3            6     66   540   6.0           9   8  17
14               51.3            6     66   540   6.0           4   4   8
15               54.9            8     88   720   8.0          19  15  34
16               43.3            6     66   540   6.0           7   6  13
17               59.8           13    143  1170  13.0          31  23  54
18               59.2            6     66   540   6.0           8   6  14
19               48.0           12    132  1080  12.0          14   9  23
20               56.4           10    110   900  10.0          26  20  46
21               56.8            8     88   720   8.0          15  12  27
22               47.5            8     88   720   8.0          12   7  19
23               38.5            6     66   540   6.0           2   1   3
24               50.0            8     88   720   8.0          13  12  25
25               40.0            6     66   540   6.0           5   3   8
26               53.7           12    132  1080  12.0          26  21  47
27               50.7            6     66   540   6.0           6   5  11
28               42.3            6     66   540   6.0           8   7  15
29               45.3            6     66   540   6.0           8   5  13
30               50.6            8     88   720   8.0           8   7  15
31               29.5            6     66   540   6.0           5   4   9

                           Expected                      Progression       \
   G-PK PK PKatt CrdY CrdR       xG  npxG   xAG npxG+xAG        PrgC PrgP
0    10  1     1   15    1      8.3   7.5   6.3     13.8          80  234
1     4  0     2   11    0      9.5   7.8   5.3     13.2         111  286
2    12  0     0    9    0      9.9   9.9   8.2     18.1         167  358
3    20  1     1   20    1     19.4  18.6  15.5     34.1         249  541
4    20  5     5   19    0     19.2  15.3  12.2     27.5         187  455
5     3  0     1    7    0      9.2   8.4   6.6     14.9          98  300
6    10  2     2   24    1     16.2  14.6  11.8     26.4         211  512
7     7  1     2   27    1      8.0   6.4   5.2     11.7         109  239
8     4  0     0   13    0      4.2   4.2   3.2      7.4         107  194
9    11  0     0   17    0     10.5  10.5   8.8     19.3         159  300
10    6  1     1   18    2      8.0   7.3   5.5     12.8         140  258
11    1  0     0   12    1      4.8   4.8   3.5      8.3          73  142
12   18  1     1   25    0     17.9  17.5  14.3     31.8         204  440
13    9  0     0   14    0      8.6   8.6   7.0     15.6         120  277
14    4  0     2   18    1      9.0   7.4   6.3     13.7         138  260
15   18  1     1   10    0     14.7  13.9  10.8     24.7         150  407
16    6  1     1   14    0      6.4   5.6   5.2     10.9         107  213
17   29  2     5   21    1     26.5  22.6  17.8     40.5         332  644
18    7  1     1   10    1      8.6   7.9   5.3     13.2         129  324
19   12  2     3   28    1     16.5  14.1  11.3     25.4         217  378
20   22  4     8   19    1     25.2  19.1  15.7     34.8         260  419
21   14  1     1   14    0     10.8  10.0   7.1     17.1         184  352
22    9  3     3   22    3     15.2  12.9  10.6     23.5         144  249
23    1  1     1   10    1      4.9   4.1   2.7      6.8          62  139
24   13  0     0    8    0     11.7  11.7  10.2     21.8         126  336
25    4  1     1   11    0      8.3   7.5   5.9     13.4          86  171
26   23  3     3   14    0     22.3  20.5  17.2     37.7         284  494
27    6  0     0   12    0      5.4   5.4   4.0      9.4          74  233
28    8  0     0   15    0      3.7   3.7   3.0      6.8         104  140
29    8  0     0   17    3      3.8   3.8   3.0      6.7          78  139
30    7  1     2   20    1     10.0   8.4   7.5     15.9         152  355
31    4  1     1   12    1      5.5   4.8   3.5      8.3          68  127

   Per 90 Minutes
              Gls   Ast   G+A  G-PK G+A-PK    xG   xAG xG+xAG  npxG npxG+xAG
0            1.83  1.50  3.33  1.67   3.17  1.39  1.04   2.43  1.26     2.30
1            0.67  0.50  1.17  0.67   1.17  1.59  0.88   2.47  1.31     2.19
2            2.00  1.67  3.67  2.00   3.67  1.65  1.36   3.01  1.65     3.01
3            2.10  1.90  4.00  2.00   3.90  1.94  1.55   3.49  1.86     3.41
4            2.50  1.60  4.10  2.00   3.60  1.92  1.22   3.14  1.53     2.75
5            0.50  0.17  0.67  0.50   0.67  1.53  1.09   2.62  1.40     2.49
6            1.20  0.70  1.90  1.00   1.70  1.62  1.18   2.80  1.46     2.64
7            1.00  0.87  1.87  0.87   1.75  1.00  0.65   1.65  0.80     1.46
8            0.67  0.33  1.00  0.67   1.00  0.70  0.54   1.24  0.70     1.24
9            1.37  1.25  2.62  1.37   2.62  1.31  1.10   2.41  1.31     2.41
10           0.87  0.62  1.50  0.75   1.37  1.01  0.69   1.69  0.91     1.59
11           0.17  0.17  0.33  0.17   0.33  0.80  0.59   1.39  0.80     1.39
12           1.46  1.31  2.77  1.38   2.69  1.38  1.10   2.48  1.34     2.45
13           1.50  1.33  2.83  1.50   2.83  1.43  1.17   2.60  1.43     2.60
14           0.67  0.67  1.33  0.67   1.33  1.50  1.05   2.55  1.24     2.29
15           2.37  1.87  4.25  2.25   4.12  1.84  1.34   3.18  1.74     3.09
16           1.17  1.00  2.17  1.00   2.00  1.07  0.87   1.94  0.94     1.81
17           2.38  1.77  4.15  2.23   4.00  2.04  1.37   3.41  1.74     3.11
18           1.33  1.00  2.33  1.17   2.17  1.44  0.88   2.32  1.31     2.19
19           1.17  0.75  1.92  1.00   1.75  1.38  0.94   2.31  1.18     2.12
20           2.60  2.00  4.60  2.20   4.20  2.52  1.57   4.09  1.91     3.48
21           1.87  1.50  3.38  1.75   3.25  1.35  0.89   2.24  1.25     2.14
22           1.50  0.87  2.37  1.13   2.00  1.90  1.33   3.23  1.61     2.94
23           0.33  0.17  0.50  0.17   0.33  0.82  0.44   1.26  0.68     1.13
24           1.62  1.50  3.12  1.62   3.12  1.46  1.27   2.73  1.46     2.73
25           0.83  0.50  1.33  0.67   1.17  1.38  0.98   2.36  1.25     2.23
26           2.17  1.75  3.92  1.92   3.67  1.85  1.43   3.28  1.71     3.14
27           1.00  0.83  1.83  1.00   1.83  0.90  0.67   1.57  0.90     1.57
28           1.33  1.17  2.50  1.33   2.50  0.62  0.50   1.13  0.62     1.13
29           1.33  0.83  2.17  1.33   2.17  0.63  0.50   1.12  0.63     1.12
30           1.00  0.87  1.87  0.87   1.75  1.25  0.94   2.19  1.05     1.99
31           0.83  0.67  1.50  0.67   1.33  0.92  0.59   1.51  0.79     1.38

In [56]:
ucl_fixtures = 'https://fbref.com/en/comps/8/2022-2023/schedule/2022-2023-Champions-League-Scores-and-Fixtures'
data = requests.get(ucl_fixtures)
ucl_results = pd.read_html(data.text)[0]

In [57]:
ucl_results

,Round,Wk,Day,Date,Time,Home,xG,Score,xG.1,Away,Attendance,Venue,Referee,Match Report,Notes
0,Group stage,1,Tue,2022-09-06,18:45,Dinamo Zagreb hr,0.6,1‚Äì0,0.9,eng Chelsea,20607,Stadion Maksimir,Istv√°n Kov√°cs,Match Report,NaN
1,Group stage,1,Tue,2022-09-06,18:45,Dortmund de,2.3,3‚Äì0,0.5,dk FC Copenhagen,70700,Signal Iduna Park,Fran√ßois Letexier,Match Report,NaN
2,Group stage,1,Tue,2022-09-06,20:00,Celtic sct,1.4,0‚Äì3,1.9,es Real Madrid,57057,Celtic Park,Sandro Sch√§rer,Match Report,NaN
3,Group stage,1,Tue,2022-09-06,20:00,Benfica pt,1.1,2‚Äì0,0.2,il Maccabi Haifa,55130,Est√°dio do Sport Lisboa e Benfica,Andreas Ekberg,Match Report,NaN
4,Group stage,1,Tue,2022-09-06,21:00,RB Salzburg at,1.3,1‚Äì1,0.9,it Milan,29520,Red Bull Arena,Srƒëan Jovanoviƒá,Match Report,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,Round,Wk,Day,Date,Time,Home,xG,Score,xG,Away,Attendance,Venue,Referee,Match Report,Notes
128,Semi-finals,NaN,Wed,2023-05-10,21:00,Milan it,0.9,0‚Äì2,2.0,it Inter,75532,Stadio Giuseppe Meazza,Jes√∫s Gil,Match Report,Leg 1 of 2
129,Semi-finals,NaN,Tue,2023-05-16,21:00,Inter it,1.0,1‚Äì0,0.5,it Milan,75567,Stadio Giuseppe Meazza,Cl√©ment Turpin,Match Report,Leg 2 of 2; Inter won
130,Semi-finals,NaN,Wed,2023-05-17,20:00,Manchester City eng,2.8,4‚Äì0,0.5,es Real Madrid,52313,Etihad Stadium,Szymon Marciniak,Match Report,Leg 2 of 2; Manchester City won
131,Final,NaN,Sat,2023-06-10,22:00,Manchester City eng,1.0,1‚Äì0,1.7,it Inter,71412,Atat√ºrk Olimpiyat Stadƒ± (Neutral Site),Szymon Marciniak,Match Report,NaN

In [58]:
ucl_teams.to_json('../data/ucl_teams.json', orient='records')
ucl_results.to_json('../data/ucl_results.json', orient='records')

# DATA PREPROCESSING

In [59]:
Results = ucl_results.copy()

Results['ResultID'] = Results.index + 1
Results = Results[['ResultID', 'Round', 'Date', 'Home', 'Score', 'Away', 'Venue', 'Referee']]
Results.dropna(subset=['Round'], inplace=True)

In [60]:
Results['Home'] = Results['Home'].str.rsplit(' ',1).str[0]
Results['Away'] = Results['Away'].str.split(' ',1).str[1]
Results = Results[Results['Date'] != 'Date']

In [62]:
Results

,ResultID,Round,Date,Home,Score,Away,Venue,Referee
0,1,Group stage,2022-09-06,Dinamo Zagreb,1‚Äì0,Chelsea,Stadion Maksimir,Istv√°n Kov√°cs
1,2,Group stage,2022-09-06,Dortmund,3‚Äì0,FC Copenhagen,Signal Iduna Park,Fran√ßois Letexier
2,3,Group stage,2022-09-06,Celtic,0‚Äì3,Real Madrid,Celtic Park,Sandro Sch√§rer
3,4,Group stage,2022-09-06,Benfica,2‚Äì0,Maccabi Haifa,Est√°dio do Sport Lisboa e Benfica,Andreas Ekberg
4,5,Group stage,2022-09-06,RB Salzburg,1‚Äì1,Milan,Red Bull Arena,Srƒëan Jovanoviƒá
...,...,...,...,...,...,...,...,...
126,127,Semi-finals,2023-05-09,Real Madrid,1‚Äì1,Manchester City,Estadio Santiago Bernab√©u,Artur Dias
128,129,Semi-finals,2023-05-10,Milan,0‚Äì2,Inter,Stadio Giuseppe Meazza,Jes√∫s Gil
129,130,Semi-finals,2023-05-16,Inter,1‚Äì0,Milan,Stadio Giuseppe Meazza,Cl√©ment Turpin
130,131,Semi-finals,2023-05-17,Manchester City,4‚Äì0,Real Madrid,Etihad Stadium,Szymon Marciniak
131,132,Final,2023-06-10,Manchester City,1‚Äì0,Inter,Atat√ºrk Olimpiyat Stadƒ± (Neutral Site),Szymon Marciniak

In [63]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
Referee = pd.DataFrame(Results['Referee'].unique(),columns=['RefereeName'])
Referee['RefereeID'] = label_encoder.fit_transform(Referee['RefereeName'])

Results['Referee'] = label_encoder.transform(Results['Referee'])
Results = Results.rename(columns={'Referee' : 'RefereeID'})
Referee['Age'] = [30,23,56,43,53,34,65,54,34,12,43,65,32,54,23,34,66,43,32,45,32,34,54,23,34,53,34,23,54,23,43,12,44,32,14,54,23,53,44,34,54]
Referee['Nation'] = 'Nation'
Referee = Referee [['RefereeID', 'RefereeName','Age','Nation']]
Referee = Referee[Referee['RefereeName'] != 'Referee']

In [65]:
Referee

    RefereeID              RefereeName  Age  Nation
0          22            Istv√°n Kov√°cs   30  Nation
1          18        Fran√ßois Letexier   23  Nation
2          33           Sandro Sch√§rer   56  Nation
3           2           Andreas Ekberg   43  Nation
4          36          Srƒëan Jovanoviƒá   53  Nation
5          14             Davide Massa   34  Nation
6          26            Jo√£o Pinheiro   65  Nation
7           4           Anthony Taylor   54  Nation
8          39           Tobias Stieler   34  Nation
9          31           Orel Grinfeeld   12  Nation
10         35            Slavko Vinƒçiƒç   43  Nation
11          9         Carlos del Cerro   65  Nation
12         38         Szymon Marciniak   32  Nation
13         27          Lawrence Visser   54  Nation
14         10           Cl√©ment Turpin   23  Nation
15         21             Irfan Peljto   34  Nation
16          6               Artur Dias   66  Nation
17          1  Anastasios Sidiropoulos   43  Nation
18         29           Michael Oliver   32  Nation
19         25             Jos√© S√°nchez   45  Nation
20         13           Danny Makkelie   32  Nation
21         24                Jes√∫s Gil   34  Nation
22         19             Glenn Nyberg   54  Nation
23          5            Antonio Mat√©u   23  Nation
24         23            Ivan Kru≈æliak   34  Nation
25         12           Daniele Orsato   53  Nation
26         17             Felix Zwayer   34  Nation
27         28         Maurizio Mariani   23  Nation
28         11           Daniel Siebert   54  Nation
29         30         Nikola Dabanoviƒá   23  Nation
30         16      Espen Andreas Esk√•s   43  Nation
31          3         Andris Treimanis   12  Nation
32         15           Donatas Rum≈°as   44  Nation
33         20         Halil Umut Meler   32  Nation
34          0      Alejandro Hern√°ndez   14  Nation
35          7       Bartosz Frankowski   54  Nation
36          8           Beno√Æt Bastien   23  Nation
37         34         Serdar G√∂z√ºb√ºy√ºk   53  Nation
38         32            Radu Petrescu   44  Nation
39         37       St√©phanie Frappart   34  Nation
40         40            ∆èliyar Aƒüayev   54  Nation

In [66]:
Stadium = pd.DataFrame(Results['Venue'].unique(), columns=['StadiumName'])
Stadium['StadiumID'] = label_encoder.fit_transform(Stadium['StadiumName'])

Results['Venue'] = label_encoder.transform(Results['Venue'])
Results = Results.rename(columns={'Venue' : 'StadiumID'})
Stadium['Country'] = ['Croatia','Germany','UK','Portugal','USA','Spain','France','Netherlands','Netherlands','UK','Italy','Spain','Spain','Italy','Belgium','Portugal','Czechia','UK','Portugal','Germany','France','Germany','Poland','UK','UK','UK','Denmark','Germany','Spain','Israel','Portugal','Turkey']
Stadium = Stadium[['StadiumID', 'StadiumName','Country']]
Stadium = Stadium[Stadium['StadiumName'] != 'Venue']

In [67]:
Stadium

    StadiumID                                  StadiumName      Country
0          28                             Stadion Maksimir      Croatia
1          25                            Signal Iduna Park      Germany
2           6                                  Celtic Park           UK
3          15            Est√°dio do Sport Lisboa e Benfica     Portugal
4          23                               Red Bull Arena          USA
5          10                Estadio Ram√≥n S√°nchez Pizju√°n        Spain
6          21                             Parc des Princes       France
7          19                           Johan Cruyff ArenA  Netherlands
8           7                           Deutsche Bank Park  Netherlands
9          31                    Tottenham Hotspur Stadium           UK
10         26                Stadio Diego Armando Maradona        Italy
11          9                Estadio C√≠vitas Metropolitano        Spain
12          5                                     Camp Nou        Spain
13         27                       Stadio Giuseppe Meazza        Italy
14         18                           Jan Breydelstadion      Belgium
15         13                        Est√°dio Jos√© Alvalade     Portugal
16          8                                 Doosan Arena      Czechia
17          2                                      Anfield           UK
18         12                            Est√°dio Do Drag√£o     Portugal
19          4                                     BayArena      Germany
20         20                             Orange V√©lodrome       France
21          0                                Allianz Arena      Germany
22         29  Stadion Miejski Legii Warszawa im. Marsz...       Poland
23         17                                Ibrox Stadium           UK
24         30                              Stamford Bridge           UK
25         16                               Etihad Stadium           UK
26         22                                       Parken      Denmark
27          1                              Allianz Stadium      Germany
28         11                    Estadio Santiago Bernab√©u        Spain
29         24                           Sammy Ofer Stadium       Israel
30         14                        Est√°dio da Luz (1954)     Portugal
31          3       Atat√ºrk Olimpiyat Stadƒ± (Neutral Site)       Turkey

In [68]:
ucl_teams
Teams = ucl_teams[[('Unnamed: 0_level_0', 'Squad' ),('Unnamed: 1_level_0','# Pl'), ('Playing Time', 'MP'), ('Performance','Gls'), ('Performance','Ast')]]
Teams.columns = Teams.columns.droplevel(0)

Teams = Teams.rename(columns= {'Squad': 'TeamName', '# Pl' : 'NumPlayers', 'MP' : 'MatchPlayed',  'Gls' : 'Goals', 'Ast' : 'Assists'})
Teams

               TeamName  NumPlayers  MatchPlayed  Goals  Assists
0               nl Ajax          19            6     11        9
1    es Atl√©tico Madrid          22            6      4        3
2          es Barcelona          26            6     12       10
3      de Bayern Munich          24           10     21       19
4            pt Benfica          24           10     25       16
5            sct Celtic          22            6      3        1
6           eng Chelsea          26           10     12        7
7        be Club Brugge          25            8      8        7
8      hr Dinamo Zagreb          20            6      4        2
9           de Dortmund          26            8     11       10
10    de Eint Frankfurt          22            8      7        5
11     dk FC Copenhagen          25            6      1        1
12             it Inter          22           13     19       17
13          it Juventus          26            6      9        8
14        de Leverkusen          20            6      4        4
15        eng Liverpool          25            8     19       15
16     il Maccabi Haifa          20            6      7        6
17  eng Manchester City          23           13     31       23
18         fr Marseille          19            6      8        6
19             it Milan          23           12     14        9
20            it Napoli          22           10     26       20
21         fr Paris S-G          21            8     15       12
22             pt Porto          24            8     12        7
23          sct Rangers          22            6      2        1
24        de RB Leipzig          22            8     13       12
25       at RB Salzburg          19            6      5        3
26       es Real Madrid          22           12     26       21
27           es Sevilla          24            6      6        5
28          ua Shakhtar          20            6      8        7
29       pt Sporting CP          25            6      8        5
30        eng Tottenham          25            8      8        7
31    cz Viktoria Plze≈à          22            6      5        4

In [69]:
Teams['Nation'] = Teams['TeamName'].map(lambda x : x.split()[0])
Teams['TeamName'] = Teams['TeamName'].str.split(' ',1).str[1]
Teams = Teams[['TeamName', 'Nation','NumPlayers','MatchPlayed','Goals','Assists']]
Teams

           TeamName Nation  NumPlayers  MatchPlayed  Goals  Assists
0              Ajax     nl          19            6     11        9
1   Atl√©tico Madrid     es          22            6      4        3
2         Barcelona     es          26            6     12       10
3     Bayern Munich     de          24           10     21       19
4           Benfica     pt          24           10     25       16
5            Celtic    sct          22            6      3        1
6           Chelsea    eng          26           10     12        7
7       Club Brugge     be          25            8      8        7
8     Dinamo Zagreb     hr          20            6      4        2
9          Dortmund     de          26            8     11       10
10   Eint Frankfurt     de          22            8      7        5
11    FC Copenhagen     dk          25            6      1        1
12            Inter     it          22           13     19       17
13         Juventus     it          26            6      9        8
14       Leverkusen     de          20            6      4        4
15        Liverpool    eng          25            8     19       15
16    Maccabi Haifa     il          20            6      7        6
17  Manchester City    eng          23           13     31       23
18        Marseille     fr          19            6      8        6
19            Milan     it          23           12     14        9
20           Napoli     it          22           10     26       20
21        Paris S-G     fr          21            8     15       12
22            Porto     pt          24            8     12        7
23          Rangers    sct          22            6      2        1
24       RB Leipzig     de          22            8     13       12
25      RB Salzburg     at          19            6      5        3
26      Real Madrid     es          22           12     26       21
27          Sevilla     es          24            6      6        5
28         Shakhtar     ua          20            6      8        7
29      Sporting CP     pt          25            6      8        5
30        Tottenham    eng          25            8      8        7
31   Viktoria Plze≈à     cz          22            6      5        4

In [70]:
import pycountry

def convert_country_code(code):
    try:
        if len(code)==2 :
            country = pycountry.countries.get(alpha_2 = code)
        elif len(code) == 3:
            country = pycountry.countries.get(alpha_3 = code)
        return country.name
    except AttributeError:
        return 'England'
    
#Teams['Nation'] = Teams['TeamName'].map(lambda x : convert_to_country_name(x.split()[0]))
Teams['Nation'] = Teams['Nation'].apply(convert_country_code)

In [71]:
Teams

           TeamName       Nation  NumPlayers  MatchPlayed  Goals  Assists
0              Ajax  Netherlands          19            6     11        9
1   Atl√©tico Madrid        Spain          22            6      4        3
2         Barcelona        Spain          26            6     12       10
3     Bayern Munich      Germany          24           10     21       19
4           Benfica     Portugal          24           10     25       16
5            Celtic      England          22            6      3        1
6           Chelsea      England          26           10     12        7
7       Club Brugge      Belgium          25            8      8        7
8     Dinamo Zagreb      Croatia          20            6      4        2
9          Dortmund      Germany          26            8     11       10
10   Eint Frankfurt      Germany          22            8      7        5
11    FC Copenhagen      Denmark          25            6      1        1
12            Inter        Italy          22           13     19       17
13         Juventus        Italy          26            6      9        8
14       Leverkusen      Germany          20            6      4        4
15        Liverpool      England          25            8     19       15
16    Maccabi Haifa       Israel          20            6      7        6
17  Manchester City      England          23           13     31       23
18        Marseille       France          19            6      8        6
19            Milan        Italy          23           12     14        9
20           Napoli        Italy          22           10     26       20
21        Paris S-G       France          21            8     15       12
22            Porto     Portugal          24            8     12        7
23          Rangers      England          22            6      2        1
24       RB Leipzig      Germany          22            8     13       12
25      RB Salzburg      Austria          19            6      5        3
26      Real Madrid        Spain          22           12     26       21
27          Sevilla        Spain          24            6      6        5
28         Shakhtar      Ukraine          20            6      8        7
29      Sporting CP     Portugal          25            6      8        5
30        Tottenham      England          25            8      8        7
31   Viktoria Plze≈à      Czechia          22            6      5        4


### Tabel yang dihasilkan :

##### 1. Teams
##### 2. Results
##### 3. Referee
##### 4. Stadium

In [72]:
Teams.to_csv('Teams.csv', index=False)
Results.to_csv('Results.csv', index=False)
Referee.to_csv('Referee.csv', index=False)
Stadium.to_csv('Stadium.csv',index=False)

# Database Modeling

In [74]:
import mysql.connector

con = mysql.connector.connect(
    host='localhost',
    user = 'root',
    password = '******',
    database = 'championsleague'
)

interact = con.cursor()

In [75]:
interact.execute('DROP TABLE IF EXISTS teams')

interact.execute('''
    CREATE TABLE teams (
        TeamName VARCHAR(100) PRIMARY KEY,
        Nation VARCHAR(100),
        NumPlayers INTEGER,
        MatchPlayed INTEGER,
        Goals INTEGER,
        Assists INTEGER
    )
''')

In [76]:
interact.execute('DROP TABLE IF EXISTS stadium')

interact.execute('''
    CREATE TABLE stadium (
        StadiumID INTEGER PRIMARY KEY,
        StadiumName VARCHAR(100),
        Country VARCHAR(100)
    )
''')

In [77]:
interact.execute('DROP TABLE IF EXISTS referee')

interact.execute('''
    CREATE TABLE referee (
        RefereeID INTEGER PRIMARY KEY,
        RefereeName VARCHAR(100),
        Age INTEGER,
        Nation VARCHAR(100)
    )
''')

In [78]:
interact.execute('DROP TABLE IF EXISTS results')

interact.execute('''
    CREATE TABLE results (
        ResultID INTEGER PRIMARY KEY,
        Round VARCHAR(100),
        Date DATE,
        Home VARCHAR(100),
        Score VARCHAR(100),
        Away VARCHAR(100),
        StadiumID INTEGER,
        RefereeID INTEGER,
        FOREIGN KEY (Home) REFERENCES teams(TeamName),
        FOREIGN KEY (Away) REFERENCES teams(TeamName),
        FOREIGN KEY (StadiumID) REFERENCES stadium(StadiumID),
        FOREIGN KEY (RefereeID) REFERENCES referee(RefereeID)
    )
''')

# Data Storing

In [79]:
from sqlalchemy import create_engine

engine = create_engine('mysql+mysqlconnector://root:******@localhost/championsleague')

In [80]:
Teams.to_sql('teams', engine, if_exists='append', index=False)
Stadium.to_sql('stadium', engine, if_exists='append', index=False)
Referee.to_sql('referee', engine, if_exists='append', index=False)
Results.to_sql('results', engine, if_exists='append', index=False)

125

In [ ]:
con.close()